#spring.application.name=JournalApp

spring:
  application:
    name: JournalApp
  data:
    mongodb:
      uri: mongodb+srv://ronystars670_db_user:Jtq3BGMAuWNVvVDm@cluster0.vpk8dnb.mongodb.net/journaldb?retryWrites=true&w=majority
      
      database: journaldb
      
      auto-index-creation: true


server:
  port: 8080
  servlet:
    context-path: /journal